# Generated by Django 3.0.7 on 2020-06-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageFile', models.ImageField(blank=True, null=True, upload_to='plant_images/%Y/%m/%d')),
                ('PerdictedDisease', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
