# Generated by Django 3.0.3 on 2020-06-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdisease',
            name='ImageFile',
            field=models.FileField(blank=True, null=True, upload_to='plant_images/%Y/%m/%d'),
        ),
    ]
